[package]
name = "kmipkit-ffi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Stable C ABI for KMIPKit"
publish = false

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
kmipkit.workspace = true
kmipkit-client.workspace = true
kmipkit-protocol.workspace = true
kmipkit-ttlv.workspace = true

[lints]
workspace = true
