// @generated by tools/api_manifest/generate.py; do not edit.
#![allow(non_camel_case_types, non_snake_case)]

pub const PUBLIC_API_MANIFEST_FORMAT_VERSION: u32 = 1;
#[repr(C)]
pub struct kmipkit_extension_identity_t { _private: [u8; 0] }

#[repr(C)]
pub struct kmipkit_extension_compatibility_t { _private: [u8; 0] }

#[repr(C)]
pub struct kmipkit_ttlv_path_t { _private: [u8; 0] }

#[repr(C)]
pub struct kmipkit_extension_discriminator_t { _private: [u8; 0] }

#[repr(C)]
pub struct kmipkit_extension_schema_t { _private: [u8; 0] }

#[repr(C)]
pub struct kmipkit_extension_information_t { _private: [u8; 0] }

#[repr(C)]
pub struct kmipkit_extension_registry_limits_t {
    pub max_definitions: u64,
    pub max_schema_nodes: u64,
    pub max_child_rules_per_structure: u64,
    pub max_text_bytes_per_field: u64,
    pub max_registry_text_bytes: u64,
    pub max_discriminator_scalar_bytes: u64,
    pub max_total_discriminator_scalar_bytes: u64,
    pub max_constraint_members_per_rule: u64,
    pub max_total_constraint_members: u64,
    pub max_payload_index_records: u64,
    pub max_lookup_comparisons: u64,
    pub max_depth: u64,
}

#[repr(C)]
pub struct kmipkit_extension_definition_t { _private: [u8; 0] }

#[repr(C)]
pub struct kmipkit_client_extension_registry_t { _private: [u8; 0] }

#[repr(C)]
pub struct kmipkit_client_configuration_t { _private: [u8; 0] }

#[repr(C)]
pub struct kmipkit_validated_extension_value_t { _private: [u8; 0] }

#[repr(C)]
pub struct kmipkit_client_request_message_extension_t { _private: [u8; 0] }

#[repr(C)]
pub struct kmipkit_ttlv_structure_t { _private: [u8; 0] }

#[repr(C)]
pub struct kmipkit_client_batch_item_t { _private: [u8; 0] }

#[repr(C)]
pub struct kmipkit_extension_child_rule_t { _private: [u8; 0] }

#[repr(C)]
pub struct kmipkit_extension_order_constraint_t { _private: [u8; 0] }

pub type kmipkit_ttlv_item_type_t = u8;
pub const KMIPKIT_TTLV_ITEM_TYPE_STRUCTURE: kmipkit_ttlv_item_type_t = 1;
pub const KMIPKIT_TTLV_ITEM_TYPE_INTEGER: kmipkit_ttlv_item_type_t = 2;
pub const KMIPKIT_TTLV_ITEM_TYPE_LONG_INTEGER: kmipkit_ttlv_item_type_t = 3;
pub const KMIPKIT_TTLV_ITEM_TYPE_BIG_INTEGER: kmipkit_ttlv_item_type_t = 4;
pub const KMIPKIT_TTLV_ITEM_TYPE_ENUMERATION: kmipkit_ttlv_item_type_t = 5;
pub const KMIPKIT_TTLV_ITEM_TYPE_BOOLEAN: kmipkit_ttlv_item_type_t = 6;
pub const KMIPKIT_TTLV_ITEM_TYPE_TEXT_STRING: kmipkit_ttlv_item_type_t = 7;
pub const KMIPKIT_TTLV_ITEM_TYPE_BYTE_STRING: kmipkit_ttlv_item_type_t = 8;
pub const KMIPKIT_TTLV_ITEM_TYPE_DATE_TIME: kmipkit_ttlv_item_type_t = 9;
pub const KMIPKIT_TTLV_ITEM_TYPE_INTERVAL: kmipkit_ttlv_item_type_t = 10;
pub const KMIPKIT_TTLV_ITEM_TYPE_DATE_TIME_EXTENDED: kmipkit_ttlv_item_type_t = 11;

#[repr(C)]
pub struct kmipkit_ttlv_value_t { _private: [u8; 0] }

#[repr(C)]
pub struct kmipkit_extension_recognition_t { _private: [u8; 0] }

#[repr(C)]
pub struct kmipkit_raw_tag_t { _private: [u8; 0] }

#[repr(C)]
pub struct kmipkit_tag_t { _private: [u8; 0] }

#[repr(C)]
pub struct kmipkit_ttlv_item_t { _private: [u8; 0] }

#[repr(C)]
pub struct kmipkit_codec_limits_t { _private: [u8; 0] }

#[repr(C)]
pub struct kmipkit_ttlv_structure_view_t { _private: [u8; 0] }

#[repr(C)]
pub struct kmipkit_ttlv_item_view_t { _private: [u8; 0] }

#[repr(C)]
pub struct kmipkit_ttlv_value_view_t { _private: [u8; 0] }

unsafe extern "C" {
    pub fn kmipkit_extension_identity_release(handle: *mut kmipkit_extension_identity_t);
    pub fn kmipkit_extension_compatibility_release(handle: *mut kmipkit_extension_compatibility_t);
    pub fn kmipkit_ttlv_path_release(handle: *mut kmipkit_ttlv_path_t);
    pub fn kmipkit_extension_discriminator_release(handle: *mut kmipkit_extension_discriminator_t);
    pub fn kmipkit_extension_schema_release(handle: *mut kmipkit_extension_schema_t);
    pub fn kmipkit_extension_information_release(handle: *mut kmipkit_extension_information_t);
    pub fn kmipkit_extension_definition_release(handle: *mut kmipkit_extension_definition_t);
    pub fn kmipkit_client_extension_registry_release(handle: *mut kmipkit_client_extension_registry_t);
    pub fn kmipkit_client_configuration_release(handle: *mut kmipkit_client_configuration_t);
    pub fn kmipkit_validated_extension_value_release(handle: *mut kmipkit_validated_extension_value_t);
    pub fn kmipkit_client_request_message_extension_release(handle: *mut kmipkit_client_request_message_extension_t);
    pub fn kmipkit_ttlv_structure_release(handle: *mut kmipkit_ttlv_structure_t);
    pub fn kmipkit_client_batch_item_release(handle: *mut kmipkit_client_batch_item_t);
    pub fn kmipkit_extension_child_rule_release(handle: *mut kmipkit_extension_child_rule_t);
    pub fn kmipkit_extension_order_constraint_release(handle: *mut kmipkit_extension_order_constraint_t);
    pub fn kmipkit_ttlv_value_release(handle: *mut kmipkit_ttlv_value_t);
    pub fn kmipkit_extension_recognition_release(handle: *mut kmipkit_extension_recognition_t);
    pub fn kmipkit_raw_tag_release(handle: *mut kmipkit_raw_tag_t);
    pub fn kmipkit_tag_release(handle: *mut kmipkit_tag_t);
    pub fn kmipkit_ttlv_item_release(handle: *mut kmipkit_ttlv_item_t);
    pub fn kmipkit_codec_limits_release(handle: *mut kmipkit_codec_limits_t);
    pub fn kmipkit_ttlv_structure_view_release(handle: *mut kmipkit_ttlv_structure_view_t);
    pub fn kmipkit_ttlv_item_view_release(handle: *mut kmipkit_ttlv_item_view_t);
    pub fn kmipkit_ttlv_value_view_release(handle: *mut kmipkit_ttlv_value_view_t);
    // KMIPKIT-0012-FR-002, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_extension_identity_create(vendor_identifier_data: *const u8, vendor_identifier_length: u64, name_data: *const u8, name_length: u64, version_data: *const u8, version_length: u64, out_identity: *mut *mut kmipkit_extension_identity_t) -> i32;
    // KMIPKIT-0012-FR-002, KMIPKIT-0012-FR-003, KMIPKIT-0012-FR-004, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_extension_definition_create(identity: *mut kmipkit_extension_identity_t, compatibility: *mut kmipkit_extension_compatibility_t, discriminator: *mut kmipkit_extension_discriminator_t, schema: *mut kmipkit_extension_schema_t, out_definition: *mut *mut kmipkit_extension_definition_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-011, KMIPKIT-0012-FR-012
    pub fn kmipkit_extension_definition_validate(definition: *mut kmipkit_extension_definition_t, value: *mut kmipkit_ttlv_structure_t, out_value: *mut *mut kmipkit_validated_extension_value_t, limits: *mut kmipkit_codec_limits_t) -> i32;
    // KMIPKIT-0012-FR-001, KMIPKIT-0012-FR-003, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_client_configuration_create(extension_registry: *mut kmipkit_client_extension_registry_t, out_configuration: *mut *mut kmipkit_client_configuration_t) -> i32;
    // KMIPKIT-0012-FR-001, KMIPKIT-0012-FR-003, KMIPKIT-0012-FR-010
    pub fn kmipkit_client_configuration_extension_registry(configuration: *mut kmipkit_client_configuration_t, out_registry: *mut *mut kmipkit_client_extension_registry_t) -> i32;
    // KMIPKIT-0012-FR-001, KMIPKIT-0012-FR-003, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_client_extension_registry_create(definitions: *mut kmipkit_extension_definition_t, definition_count: u64, max_definitions: u64, max_schema_nodes: u64, max_child_rules_per_structure: u64, max_text_bytes_per_field: u64, max_registry_text_bytes: u64, max_discriminator_scalar_bytes: u64, max_total_discriminator_scalar_bytes: u64, max_constraint_members_per_rule: u64, max_total_constraint_members: u64, max_payload_index_records: u64, max_lookup_comparisons: u64, max_depth: u64, out_registry: *mut *mut kmipkit_client_extension_registry_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-006, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-008, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_client_extension_registry_inspect(registry: *mut kmipkit_client_extension_registry_t, vendor_identifier_data: *const u8, vendor_identifier_length: u64, value: *mut kmipkit_ttlv_structure_t, out_value: *mut *mut kmipkit_extension_recognition_t, limits: *mut kmipkit_codec_limits_t) -> i32;
    // KMIPKIT-0012-FR-009, KMIPKIT-0012-FR-010
    pub fn kmipkit_client_extension_registry_definition_count(registry: *mut kmipkit_client_extension_registry_t, out_count: *mut u64) -> i32;
    // KMIPKIT-0012-FR-009, KMIPKIT-0012-FR-010
    pub fn kmipkit_client_extension_registry_definition_at(registry: *mut kmipkit_client_extension_registry_t, index: u64, out_definition: *mut *mut kmipkit_extension_definition_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-011
    pub fn kmipkit_client_request_message_extension_create(value: *mut kmipkit_validated_extension_value_t, criticality_indicator: u8, out_extension: *mut *mut kmipkit_client_request_message_extension_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-011
    pub fn kmipkit_client_batch_item_with_extension(item: *mut kmipkit_client_batch_item_t, extension: *mut kmipkit_client_request_message_extension_t, out_item: *mut *mut kmipkit_client_batch_item_t) -> i32;
    // KMIPKIT-0012-FR-002, KMIPKIT-0012-FR-003, KMIPKIT-0012-FR-010
    pub fn kmipkit_extension_compatibility_create(kmip_min_major: u8, kmip_min_minor: u8, kmip_max_major: u8, kmip_max_minor: u8, kmipkit_minimum_data: *const u8, kmipkit_minimum_length: u64, kmipkit_maximum_data: *const u8, kmipkit_maximum_length: u64, out_compatibility: *mut *mut kmipkit_extension_compatibility_t) -> i32;
    // KMIPKIT-0012-FR-002, KMIPKIT-0012-FR-006, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_ttlv_path_create(first_tag: u32, out_path: *mut *mut kmipkit_ttlv_path_t) -> i32;
    // KMIPKIT-0012-FR-002, KMIPKIT-0012-FR-006, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_ttlv_path_with_child_tag(path: *mut kmipkit_ttlv_path_t, tag: u32, out_path: *mut *mut kmipkit_ttlv_path_t) -> i32;
    // KMIPKIT-0012-FR-002, KMIPKIT-0012-FR-006, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_extension_discriminator_create(path: *mut kmipkit_ttlv_path_t, scalar_value: *mut kmipkit_ttlv_value_t, out_discriminator: *mut *mut kmipkit_extension_discriminator_t) -> i32;
    // KMIPKIT-0012-FR-004, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_extension_schema_scalar(item_type: u32, out_schema: *mut *mut kmipkit_extension_schema_t) -> i32;
    // KMIPKIT-0012-FR-004, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_extension_schema_structure(children: *mut kmipkit_extension_child_rule_t, child_count: u64, order_constraints: *mut kmipkit_extension_order_constraint_t, order_constraint_count: u64, preserve_undeclared_children: u8, out_schema: *mut *mut kmipkit_extension_schema_t) -> i32;
    // KMIPKIT-0012-FR-004, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_extension_child_rule_required(tag: u32, schema: *mut kmipkit_extension_schema_t, out_rule: *mut *mut kmipkit_extension_child_rule_t) -> i32;
    // KMIPKIT-0012-FR-004, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_extension_child_rule_optional(tag: u32, schema: *mut kmipkit_extension_schema_t, out_rule: *mut *mut kmipkit_extension_child_rule_t) -> i32;
    // KMIPKIT-0012-FR-004, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_extension_child_rule_repeated(tag: u32, schema: *mut kmipkit_extension_schema_t, out_rule: *mut *mut kmipkit_extension_child_rule_t) -> i32;
    // KMIPKIT-0012-FR-004, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_extension_order_constraint_create(before_tag: u32, after_tag: u32, out_constraint: *mut *mut kmipkit_extension_order_constraint_t) -> i32;
    // KMIPKIT-0012-FR-004, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_extension_schema_minimum_length(schema: *mut kmipkit_extension_schema_t, bytes: u64, out_schema: *mut *mut kmipkit_extension_schema_t) -> i32;
    // KMIPKIT-0012-FR-004, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_extension_schema_maximum_length(schema: *mut kmipkit_extension_schema_t, bytes: u64, out_schema: *mut *mut kmipkit_extension_schema_t) -> i32;
    // KMIPKIT-0012-FR-004, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_extension_schema_signed_numeric_range(schema: *mut kmipkit_extension_schema_t, minimum: i64, maximum: i64, out_schema: *mut *mut kmipkit_extension_schema_t) -> i32;
    // KMIPKIT-0012-FR-004, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_extension_schema_unsigned_numeric_range(schema: *mut kmipkit_extension_schema_t, minimum: u64, maximum: u64, out_schema: *mut *mut kmipkit_extension_schema_t) -> i32;
    // KMIPKIT-0012-FR-004, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_extension_schema_allowed_enumeration(schema: *mut kmipkit_extension_schema_t, value: u32, out_schema: *mut *mut kmipkit_extension_schema_t) -> i32;
    // KMIPKIT-0012-FR-004, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_extension_schema_allowed_bit_mask(schema: *mut kmipkit_extension_schema_t, value: u32, out_schema: *mut *mut kmipkit_extension_schema_t) -> i32;
    // KMIPKIT-0012-FR-004, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_extension_schema_required_bit_mask(schema: *mut kmipkit_extension_schema_t, value: u32, out_schema: *mut *mut kmipkit_extension_schema_t) -> i32;
    // KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_extension_registry_limits_default_values(out_max_definitions: *mut u64, out_max_schema_nodes: *mut u64, out_max_child_rules_per_structure: *mut u64, out_max_text_bytes_per_field: *mut u64, out_max_registry_text_bytes: *mut u64, out_max_discriminator_scalar_bytes: *mut u64, out_max_total_discriminator_scalar_bytes: *mut u64, out_max_constraint_members_per_rule: *mut u64, out_max_total_constraint_members: *mut u64, out_max_payload_index_records: *mut u64, out_max_lookup_comparisons: *mut u64, out_max_depth: *mut u64) -> i32;
    // KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_extension_registry_limits_validate(max_definitions: u64, max_schema_nodes: u64, max_child_rules_per_structure: u64, max_text_bytes_per_field: u64, max_registry_text_bytes: u64, max_discriminator_scalar_bytes: u64, max_total_discriminator_scalar_bytes: u64, max_constraint_members_per_rule: u64, max_total_constraint_members: u64, max_payload_index_records: u64, max_lookup_comparisons: u64, max_depth: u64) -> i32;
    // KMIPKIT-0012-FR-009, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_extension_information_create(extension_name_data: *const u8, extension_name_length: u64, out_information: *mut *mut kmipkit_extension_information_t) -> i32;
    // KMIPKIT-0012-FR-009, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_extension_information_tag(information: *mut kmipkit_extension_information_t, tag: u32, out_information: *mut *mut kmipkit_extension_information_t) -> i32;
    // KMIPKIT-0012-FR-009, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_extension_information_type(information: *mut kmipkit_extension_information_t, r#type: u32, out_information: *mut *mut kmipkit_extension_information_t) -> i32;
    // KMIPKIT-0012-FR-009, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_extension_information_enumeration(information: *mut kmipkit_extension_information_t, enumeration: u32, out_information: *mut *mut kmipkit_extension_information_t) -> i32;
    // KMIPKIT-0012-FR-009, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_extension_information_attribute(information: *mut kmipkit_extension_information_t, attribute: u8, out_information: *mut *mut kmipkit_extension_information_t) -> i32;
    // KMIPKIT-0012-FR-009, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_extension_information_parent_structure_tag(information: *mut kmipkit_extension_information_t, parent_structure_tag: u32, out_information: *mut *mut kmipkit_extension_information_t) -> i32;
    // KMIPKIT-0012-FR-009, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_extension_information_description(information: *mut kmipkit_extension_information_t, description_data: *const u8, description_length: u64, out_information: *mut *mut kmipkit_extension_information_t) -> i32;
    // KMIPKIT-0012-FR-009, KMIPKIT-0012-FR-010
    pub fn kmipkit_extension_information_to_ttlv(information: *mut kmipkit_extension_information_t, out_structure: *mut *mut kmipkit_ttlv_structure_t) -> i32;
    // KMIPKIT-0012-FR-009, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_extension_definition_with_information(definition: *mut kmipkit_extension_definition_t, information: *mut kmipkit_extension_information_t, out_definition: *mut *mut kmipkit_extension_definition_t) -> i32;
    // KMIPKIT-0012-FR-002, KMIPKIT-0012-FR-009, KMIPKIT-0012-FR-010
    pub fn kmipkit_extension_definition_identity(definition: *mut kmipkit_extension_definition_t, out_identity: *mut *mut kmipkit_extension_identity_t) -> i32;
    // KMIPKIT-0012-FR-009, KMIPKIT-0012-FR-010
    pub fn kmipkit_extension_definition_information(definition: *mut kmipkit_extension_definition_t, out_information: *mut *mut kmipkit_extension_information_t) -> i32;
    // KMIPKIT-0012-FR-009, KMIPKIT-0012-FR-010
    pub fn kmipkit_client_extension_registry_definition_for_identity(registry: *mut kmipkit_client_extension_registry_t, identity: *mut kmipkit_extension_identity_t, out_definition: *mut *mut kmipkit_extension_definition_t) -> i32;
    // KMIPKIT-0012-FR-006, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_extension_recognition_is_recognized(recognition: *mut kmipkit_extension_recognition_t, out_recognized: *mut u32) -> i32;
    // KMIPKIT-0012-FR-006, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_extension_recognition_validated_value(recognition: *mut kmipkit_extension_recognition_t, out_value: *mut *mut kmipkit_validated_extension_value_t) -> i32;
    // KMIPKIT-0012-FR-006, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_extension_recognition_generic_value(recognition: *mut kmipkit_extension_recognition_t, out_value: *mut *mut kmipkit_ttlv_structure_view_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_validated_extension_value_identity(value: *mut kmipkit_validated_extension_value_t, out_identity: *mut *mut kmipkit_extension_identity_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-011
    pub fn kmipkit_validated_extension_value_generic_value(value: *mut kmipkit_validated_extension_value_t, out_structure: *mut *mut kmipkit_ttlv_structure_view_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_validated_extension_value_value_at(value: *mut kmipkit_validated_extension_value_t, path: *mut kmipkit_ttlv_path_t, out_value: *mut *mut kmipkit_ttlv_value_view_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_raw_tag_create(raw: u32, out_raw_tag: *mut *mut kmipkit_raw_tag_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_raw_tag_value(raw_tag: *mut kmipkit_raw_tag_t, out_raw: *mut u32) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_raw_tag_try_checked(raw_tag: *mut kmipkit_raw_tag_t, out_tag: *mut *mut kmipkit_tag_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_tag_value(tag: *mut kmipkit_tag_t, out_raw: *mut u32) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_codec_limits_defaults(out_limits: *mut *mut kmipkit_codec_limits_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_codec_limits_create(max_message_bytes: u64, max_structure_depth: u64, max_elements: u64, out_limits: *mut *mut kmipkit_codec_limits_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_codec_limits_max_message_bytes(limits: *mut kmipkit_codec_limits_t, max_message_bytes: *mut u64) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_codec_limits_max_structure_depth(limits: *mut kmipkit_codec_limits_t, max_structure_depth: *mut u64) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_codec_limits_max_elements(limits: *mut kmipkit_codec_limits_t, max_elements: *mut u64) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_value_integer(value: i32, out_value: *mut *mut kmipkit_ttlv_value_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_value_long_integer(value: i64, out_value: *mut *mut kmipkit_ttlv_value_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_value_enumeration(value: u32, out_value: *mut *mut kmipkit_ttlv_value_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_value_boolean(value: u8, out_value: *mut *mut kmipkit_ttlv_value_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_value_date_time(value: i64, out_value: *mut *mut kmipkit_ttlv_value_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_value_interval(value: u32, out_value: *mut *mut kmipkit_ttlv_value_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_value_date_time_extended(value: i64, out_value: *mut *mut kmipkit_ttlv_value_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_ttlv_value_big_integer(limits: *mut kmipkit_codec_limits_t, value: *const u8, value_length: u64, out_value: *mut *mut kmipkit_ttlv_value_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_ttlv_value_text_string(limits: *mut kmipkit_codec_limits_t, value: *const u8, value_length: u64, out_value: *mut *mut kmipkit_ttlv_value_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_ttlv_value_byte_string(limits: *mut kmipkit_codec_limits_t, value: *const u8, value_length: u64, out_value: *mut *mut kmipkit_ttlv_value_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_ttlv_value_structure(structure: *mut kmipkit_ttlv_structure_t, limits: *mut kmipkit_codec_limits_t, out_value: *mut *mut kmipkit_ttlv_value_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_structure_create(out_structure: *mut *mut kmipkit_ttlv_structure_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_ttlv_item_create(tag: *mut kmipkit_tag_t, value: *mut kmipkit_ttlv_value_t, limits: *mut kmipkit_codec_limits_t, out_item: *mut *mut kmipkit_ttlv_item_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012
    pub fn kmipkit_ttlv_structure_with_item(structure: *mut kmipkit_ttlv_structure_t, item: *mut kmipkit_ttlv_item_t, limits: *mut kmipkit_codec_limits_t, out_structure: *mut *mut kmipkit_ttlv_structure_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_structure_view(structure: *mut kmipkit_ttlv_structure_t, out_view: *mut *mut kmipkit_ttlv_structure_view_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_structure_view_item_count(view: *mut kmipkit_ttlv_structure_view_t, out_count: *mut u64) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_structure_view_item_at(view: *mut kmipkit_ttlv_structure_view_t, index: u64, out_item: *mut *mut kmipkit_ttlv_item_view_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_item_view_tag(view: *mut kmipkit_ttlv_item_view_t, out_tag: *mut *mut kmipkit_tag_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_item_view_type(view: *mut kmipkit_ttlv_item_view_t, out_item_type: *mut u8) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_item_view_value(view: *mut kmipkit_ttlv_item_view_t, out_value: *mut *mut kmipkit_ttlv_value_view_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_value_view(value: *mut kmipkit_ttlv_value_t, out_view: *mut *mut kmipkit_ttlv_value_view_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_value_view_type(view: *mut kmipkit_ttlv_value_view_t, out_item_type: *mut u8) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_value_view_structure(view: *mut kmipkit_ttlv_value_view_t, out_structure: *mut *mut kmipkit_ttlv_structure_view_t) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_value_view_integer(view: *mut kmipkit_ttlv_value_view_t, out_value: *mut i32) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_value_view_long_integer(view: *mut kmipkit_ttlv_value_view_t, out_value: *mut i64) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_value_view_enumeration(view: *mut kmipkit_ttlv_value_view_t, out_value: *mut u32) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_value_view_boolean(view: *mut kmipkit_ttlv_value_view_t, out_value: *mut u8) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_value_view_date_time(view: *mut kmipkit_ttlv_value_view_t, out_value: *mut i64) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_value_view_interval(view: *mut kmipkit_ttlv_value_view_t, out_value: *mut u32) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_value_view_date_time_extended(view: *mut kmipkit_ttlv_value_view_t, out_value: *mut i64) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_value_view_byte_length(view: *mut kmipkit_ttlv_value_view_t, out_length: *mut u64) -> i32;
    // KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010
    pub fn kmipkit_ttlv_value_view_byte_at(view: *mut kmipkit_ttlv_value_view_t, index: u64, out_byte: *mut u8) -> i32;
}
