"""Generate Rust TTLV type constraints for catalogued KMIP attributes."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any

if __package__:
    from .safe_io import PathSecurityError, atomic_write_bytes, safe_read_bytes
    from .validate import MAX_BYTES, CatalogValidationError, load_validated_catalog
else:
    from safe_io import PathSecurityError, atomic_write_bytes, safe_read_bytes
    from validate import MAX_BYTES, CatalogValidationError, load_validated_catalog


CATALOG_PATH = "specification/catalog/kmip-2.1.json"
OUTPUT_PATH = "crates/kmipkit-protocol/src/attribute_types_generated.rs"
_VENDOR_ATTRIBUTE_ID = "KMIPKIT-ELEM-ATTRIBUTE-VENDOR-ATTRIBUTE"
_WIRE_VALUE = re.compile(r"(?:0x)?[0-9A-Fa-f]{6}\Z")
_TYPE_NAMES = {
    "Big Integer": "BigInteger",
    "Boolean": "Boolean",
    "Byte String": "ByteString",
    "Date Time": "DateTime",
    "Date-Time": "DateTime",
    "Date Time Extended": "DateTimeExtended",
    "Enumeration": "Enumeration",
    "Integer": "Integer",
    "Interval": "Interval",
    "RNG Parameters": "Structure",
    "Structure": "Structure",
    "Text String": "TextString",
}


def _attribute_encodings(catalog: dict[str, Any]) -> list[tuple[int, list[str]]]:
    elements = catalog.get("elements")
    if not isinstance(elements, list):
        raise ValueError("catalog has no element list")

    tags: dict[str, tuple[int, str, bool]] = {}
    seen_tag_values: set[int] = set()
    for element in elements:
        if not isinstance(element, dict) or element.get("kind") != "tag":
            continue
        element_id = element.get("element_id")
        wire_value = element.get("wire_value")
        if not isinstance(element_id, str) or not _WIRE_VALUE.fullmatch(str(wire_value)):
            raise ValueError("catalog tag has an invalid identity or wire value")
        numeric_value = int(str(wire_value).removeprefix("0x").removeprefix("0X"), 16)
        if element_id in tags or numeric_value in seen_tag_values:
            raise ValueError("catalog contains duplicate tag identities or values")
        allocation = element.get("allocation")
        if allocation not in {"assigned", "reserved"}:
            raise ValueError("catalog tag has an unsupported allocation")
        seen_tag_values.add(numeric_value)
        tags[element_id] = (numeric_value, str(element.get("name", "")), allocation == "assigned")

    attributes: list[tuple[int, list[str]]] = []
    seen_attribute_tags: set[int] = set()
    for element in elements:
        if not isinstance(element, dict) or element.get("kind") != "attribute":
            continue
        source_encoding = element.get("source_encoding")
        if source_encoding is None:
            continue
        if not isinstance(source_encoding, str) or not source_encoding.strip():
            raise ValueError("catalog attribute has an invalid source encoding")
        parents = element.get("parent_element_ids")
        if element.get("element_id") == _VENDOR_ATTRIBUTE_ID:
            if source_encoding != "Structure" or parents != []:
                raise ValueError("Vendor Attribute must retain its separate Table 150 structure")
            continue
        if (
            not isinstance(parents, list)
            or len(parents) != 1
            or not isinstance(parents[0], str)
            or parents[0] not in tags
        ):
            raise ValueError("catalog attribute must have exactly one tag parent")
        raw_tag, _, assigned = tags[parents[0]]
        if not assigned:
            raise ValueError("attribute parent tag is not assigned")
        if raw_tag in seen_attribute_tags:
            raise ValueError("catalog attributes share a duplicate TTLV tag")
        seen_attribute_tags.add(raw_tag)

        types = _item_types_for_encoding(source_encoding)
        attributes.append((raw_tag, types))

    if not attributes:
        raise ValueError("catalog has no typed attribute encodings")
    return sorted(attributes)


def _rust_number(value: int) -> str:
    return f"0x{value >> 16:02X}_{(value >> 8) & 0xFF:02X}_{value & 0xFF:02X}"


def _item_types_for_encoding(source_encoding: str) -> list[str]:
    names = [part.strip() for part in re.split(r",|\s+or\s+", source_encoding) if part.strip()]
    if not names or any(name not in _TYPE_NAMES for name in names):
        raise ValueError("catalog attribute has an unsupported source encoding")
    return list(dict.fromkeys(_TYPE_NAMES[name] for name in names))


def render_rust(catalog: dict[str, Any]) -> str:
    """Render a deterministic lookup table from catalog attribute encodings."""
    encodings = _attribute_encodings(catalog)
    lines = [
        "// @generated by tools/normative_catalog/generate_attribute_types.py; do not edit.",
        "use kmipkit_ttlv::ItemType;",
        "",
        "pub(super) const ATTRIBUTE_TYPES: &[(u32, &[ItemType])] = &[",
    ]
    for raw_tag, types in encodings:
        if len(types) == 1:
            lines.append(
                f"    ({_rust_number(raw_tag)}, &[ItemType::{types[0]}]),"
            )
        else:
            lines.extend([
                "    (",
                f"        {_rust_number(raw_tag)},",
                "        &[",
                *(f"            ItemType::{item_type}," for item_type in types),
                "        ],",
                "    ),",
            ])
    lines.extend([
        "];",
        "",
        "pub(super) fn expected_types(raw_tag: u32) -> Option<&'static [ItemType]> {",
        "    ATTRIBUTE_TYPES",
        "        .binary_search_by_key(&raw_tag, |(tag, _)| *tag)",
        "        .ok()",
        "        .map(|index| ATTRIBUTE_TYPES[index].1)",
        "}",
        "",
    ])
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path.cwd())
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="write the generated Rust source")
    mode.add_argument("--check", action="store_true", help="fail if generated Rust source is stale")
    arguments = parser.parse_args(argv)

    try:
        root = arguments.repo_root.resolve(strict=True)
        raw_catalog = safe_read_bytes(root, CATALOG_PATH, max_bytes=MAX_BYTES)
        catalog = load_validated_catalog(raw_catalog, root)
        generated = render_rust(catalog).encode("utf-8")
        if arguments.write:
            atomic_write_bytes(root, OUTPUT_PATH, generated)
            print(f"generated attribute TTLV types: {root / OUTPUT_PATH}")
            return 0
        existing = safe_read_bytes(root, OUTPUT_PATH, max_bytes=MAX_BYTES)
    except CatalogValidationError:
        print("attribute type generation failed: catalog validation failed", file=sys.stderr)
        return 2
    except PathSecurityError:
        print("attribute type generation failed: repository path validation failed", file=sys.stderr)
        return 2
    except OSError:
        print("attribute type generation failed: repository I/O failed", file=sys.stderr)
        return 2
    except ValueError as error:
        print(f"attribute type generation failed: {error}", file=sys.stderr)
        return 2

    if existing != generated:
        print(
            "generated attribute TTLV types are stale; run generate_attribute_types.py --write",
            file=sys.stderr,
        )
        return 1
    print(f"generated attribute TTLV types verified: {root / OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
