"""Validate and render the reviewed KMIPKit public API manifest.

The manifest and schema are read relative to ``--repo-root`` (the current
directory by default). ``--write`` atomically writes only the six destinations
fixed by the version-1 contract. ``--check`` compares generated bytes without
creating or changing files. Runtime code uses only the Python standard library.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import re
import stat
import sys
import tempfile
from decimal import Decimal
from pathlib import Path
from typing import Any


MANIFEST_PATH = "specification/api/public-api.json"
SCHEMA_PATH = "specification/api/public-api.schema.json"
MAX_MANIFEST_BYTES = 16 * 1024 * 1024
MAX_SCHEMA_BYTES = 4 * 1024 * 1024
OUTPUTS = {
    "rustFfi": "crates/kmipkit-ffi/src/extension_registry_generated.rs",
    "cHeader": "bindings/c/include/kmipkit.h",
    "javaApi": "bindings/java/src/main/java/org/kmipkit/generated/ExtensionRegistryApi.java",
    "javaParityTests": "bindings/java/src/test/java/org/kmipkit/generated/ExtensionRegistryParityFixtures.java",
    "pythonApi": "bindings/python/src/kmipkit/_generated/extension_registry.py",
    "parityFixtures": "tests/fixtures/extensions/generated/registry_parity.json",
}
_FIXED_LIMIT_IDS = (
    "maxDefinitions",
    "maxSchemaNodes",
    "maxChildRulesPerStructure",
    "maxTextBytesPerField",
    "maxRegistryTextBytes",
    "maxDiscriminatorScalarBytes",
    "maxTotalDiscriminatorScalarBytes",
    "maxConstraintMembersPerRule",
    "maxTotalConstraintMembers",
    "maxPayloadIndexRecords",
    "maxLookupComparisons",
    "maxDepth",
)
_C_INTEGER_TYPES = {
    "int8_t": ("i8", 8, True),
    "uint8_t": ("u8", 8, False),
    "int16_t": ("i16", 16, True),
    "uint16_t": ("u16", 16, False),
    "int32_t": ("i32", 32, True),
    "uint32_t": ("u32", 32, False),
    "int64_t": ("i64", 64, True),
    "uint64_t": ("u64", 64, False),
}
_REQUIREMENT_PATTERN = re.compile(r"KMIPKIT-0012-FR-[0-9]{3}\Z")
_RUST_2024_KEYWORDS = {
    "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum",
    "extern", "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod",
    "move", "mut", "pub", "ref", "return", "self", "Self", "static", "struct", "super",
    "trait", "true", "type", "unsafe", "use", "where", "while", "abstract", "become", "box",
    "do", "final", "gen", "macro", "override", "priv", "try", "typeof", "unsized", "virtual",
    "yield",
}
_RUST_RAW_IDENTIFIER_FORBIDDEN = {"_", "crate", "self", "Self", "super"}


class ManifestError(ValueError):
    """The manifest is malformed, invalid, or inconsistent with its schema."""


class PathSecurityError(ValueError):
    """An output path is unsafe or differs from the approved destination list."""


def _reject_constant(value: str) -> None:
    raise ManifestError("JSON contains a non-finite number")


def _parse_float(value: str) -> float:
    parsed = float(value)
    if not math.isfinite(parsed):
        raise ManifestError("JSON contains a non-finite number")
    return parsed


def _unique_object(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise ManifestError("JSON contains a duplicate object member")
        result[key] = value
    return result


def _dump_json(value: Any, *, indent: int | None = None) -> str:
    options: dict[str, Any] = {"ensure_ascii": False, "sort_keys": True}
    if indent is None:
        options["separators"] = (",", ":")
    else:
        options["indent"] = indent
    return json.dumps(value, **options)


def _load_json(root: Path, relative_path: str, max_bytes: int) -> Any:
    path = root / relative_path
    data = path.read_bytes()
    if len(data) > max_bytes:
        raise ManifestError("manifest input exceeds the supported file size")
    try:
        return json.loads(
            data.decode("utf-8"),
            object_pairs_hook=_unique_object,
            parse_constant=_reject_constant,
            parse_float=_parse_float,
        )
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise ManifestError("manifest input is not valid UTF-8 JSON") from error


def _json_type_matches(value: Any, expected: str) -> bool:
    if expected == "object":
        return isinstance(value, dict)
    if expected == "array":
        return isinstance(value, list)
    if expected == "string":
        return isinstance(value, str)
    if expected == "boolean":
        return isinstance(value, bool)
    if expected == "integer":
        return isinstance(value, int) and not isinstance(value, bool)
    if expected == "number":
        return isinstance(value, (int, float)) and not isinstance(value, bool)
    if expected == "null":
        return value is None
    return False


def _json_equal(left: Any, right: Any) -> bool:
    if isinstance(left, bool) or isinstance(right, bool):
        return type(left) is type(right) and left == right
    if isinstance(left, (int, float)) and isinstance(right, (int, float)):
        return left == right
    if isinstance(left, dict) and isinstance(right, dict):
        return left.keys() == right.keys() and all(_json_equal(left[key], right[key]) for key in left)
    if isinstance(left, list) and isinstance(right, list):
        return len(left) == len(right) and all(_json_equal(a, b) for a, b in zip(left, right))
    return type(left) is type(right) and left == right


def _json_hashable(value: Any) -> Any:
    if isinstance(value, bool):
        return ("boolean", value)
    if value is None:
        return ("null",)
    if isinstance(value, (int, float)):
        return ("number", Decimal(str(value)).normalize())
    if isinstance(value, str):
        return ("string", value)
    if isinstance(value, list):
        return ("array", tuple(_json_hashable(item) for item in value))
    if isinstance(value, dict):
        return ("object", tuple(sorted((key, _json_hashable(item)) for key, item in value.items())))
    raise ManifestError("JSON contains an unsupported value")


def _resolve_pointer(document: Any, reference: str) -> Any:
    if not reference.startswith("#/"):
        raise ManifestError("schema uses an unsupported external reference")
    current = document
    for part in reference[2:].split("/"):
        key = part.replace("~1", "/").replace("~0", "~")
        try:
            current = current[int(key)] if isinstance(current, list) else current[key]
        except (KeyError, IndexError, ValueError, TypeError) as error:
            raise ManifestError("schema contains an unresolved local reference") from error
    return current


def _schema_matches(
    value: Any,
    schema: Any,
    root_schema: dict[str, Any],
    path: str,
    errors: list[str],
) -> bool:
    """Validate the core Draft 2020-12 vocabulary used by the checked-in schema."""
    initial_error_count = len(errors)
    if schema is True:
        return True
    if schema is False:
        errors.append(path or "manifest")
        return False
    if not isinstance(schema, dict):
        errors.append(path or "manifest")
        return False

    if "$ref" in schema:
        referenced = _resolve_pointer(root_schema, schema["$ref"])
        _schema_matches(value, referenced, root_schema, path, errors)

    if "type" in schema:
        allowed_types = schema["type"] if isinstance(schema["type"], list) else [schema["type"]]
        if not any(_json_type_matches(value, item) for item in allowed_types):
            errors.append(path or "manifest")
            return False

    if "const" in schema and not _json_equal(value, schema["const"]):
        errors.append(path or "manifest")
    if "enum" in schema and not any(_json_equal(value, choice) for choice in schema["enum"]):
        errors.append(path or "manifest")

    for keyword in ("allOf", "anyOf", "oneOf"):
        if keyword not in schema:
            continue
        outcomes: list[bool] = []
        for child in schema[keyword]:
            child_errors: list[str] = []
            outcomes.append(_schema_matches(value, child, root_schema, path, child_errors))
        successes = sum(outcomes)
        valid = successes == len(outcomes) if keyword == "allOf" else (
            successes > 0 if keyword == "anyOf" else successes == 1
        )
        if not valid:
            errors.append(path or "manifest")

    if "not" in schema:
        child_errors: list[str] = []
        if _schema_matches(value, schema["not"], root_schema, path, child_errors):
            errors.append(path or "manifest")

    if "if" in schema:
        condition_errors: list[str] = []
        branch = "then" if _schema_matches(value, schema["if"], root_schema, path, condition_errors) else "else"
        if branch in schema:
            _schema_matches(value, schema[branch], root_schema, path, errors)

    if isinstance(value, dict):
        missing = [name for name in schema.get("required", []) if name not in value]
        for name in missing:
            errors.append(f"{path}/{name}" if path else name)
        properties = schema.get("properties", {})
        for name, child_value in value.items():
            child_schema = properties.get(name)
            if child_schema is None:
                additional = schema.get("additionalProperties", True)
                if additional is False:
                    errors.append(f"{path}/{name}" if path else name)
                elif isinstance(additional, (dict, bool)):
                    _schema_matches(
                        child_value,
                        additional,
                        root_schema,
                        f"{path}/{name}" if path else name,
                        errors,
                    )
                continue
            _schema_matches(
                child_value,
                child_schema,
                root_schema,
                f"{path}/{name}" if path else name,
                errors,
            )

    if isinstance(value, list):
        if len(value) < schema.get("minItems", 0):
            errors.append(path or "manifest")
        if len(value) > schema.get("maxItems", len(value)):
            errors.append(path or "manifest")
        for index, child_schema in enumerate(schema.get("prefixItems", [])):
            if index < len(value):
                _schema_matches(value[index], child_schema, root_schema, f"{path}/{index}", errors)
        if "items" in schema:
            start = len(schema.get("prefixItems", []))
            for index in range(start, len(value)):
                _schema_matches(value[index], schema["items"], root_schema, f"{path}/{index}", errors)
        if schema.get("uniqueItems"):
            normalized = [_json_hashable(item) for item in value]
            if len(set(normalized)) != len(normalized):
                errors.append(path or "manifest")

    if isinstance(value, str):
        if len(value) < schema.get("minLength", 0):
            errors.append(path or "manifest")
        if "pattern" in schema and re.search(schema["pattern"], value) is None:
            errors.append(path or "manifest")

    if isinstance(value, (int, float)) and not isinstance(value, bool):
        if "minimum" in schema and value < schema["minimum"]:
            errors.append(path or "manifest")
        if "maximum" in schema and value > schema["maximum"]:
            errors.append(path or "manifest")

    return len(errors) == initial_error_count


def _check_schema_subset(schema: dict[str, Any]) -> None:
    supported = {
        "$defs", "$id", "$schema", "additionalProperties", "allOf", "anyOf", "const",
        "description", "else", "enum", "format", "if", "items", "maximum", "minItems",
        "minLength", "minimum", "not", "oneOf", "pattern", "prefixItems", "properties",
        "required", "then", "title", "type", "uniqueItems", "$ref", "maxItems",
    }
    def visit(schema_node: Any) -> None:
        if isinstance(schema_node, bool):
            return
        if isinstance(schema_node, dict):
            unsupported = set(schema_node) - supported
            if unsupported:
                raise ManifestError("schema contains unsupported validation keywords")
            for name in ("$defs", "properties"):
                for child in schema_node.get(name, {}).values():
                    visit(child)
            for name in ("items", "additionalProperties", "not", "if", "then", "else"):
                child = schema_node.get(name)
                if isinstance(child, (dict, bool)):
                    visit(child)
            for name in ("allOf", "anyOf", "oneOf", "prefixItems"):
                for child in schema_node.get(name, []):
                    visit(child)
    visit(schema)


def _validate_schema(manifest: Any, schema: dict[str, Any]) -> None:
    _check_schema_subset(schema)
    errors: list[str] = []
    _schema_matches(manifest, schema, schema, "", errors)
    if errors:
        location = errors[0].replace("~", "~0").replace("/", "~1")
        raise ManifestError(f"manifest does not match the declared schema near {location}")


def _require_unique(records: list[dict[str, Any]], field: str, label: str) -> set[Any]:
    values = [record[field] for record in records]
    if len(set(values)) != len(values):
        raise ManifestError(f"manifest contains duplicate {label}")
    return set(values)


def _validate_references(manifest: dict[str, Any]) -> None:
    root_requirements = set(manifest["requirementIds"])
    error_ids = _require_unique(manifest["errorCategories"], "id", "error category IDs")
    _require_unique(manifest["types"], "id", "type IDs")
    _require_unique(manifest["functions"], "id", "function IDs")
    _require_unique(manifest["errorCategories"], "cValue", "C error values")
    _require_unique(manifest["errorCategories"], "cCode", "C error codes")
    c_symbols = [function["c"]["symbol"] for function in manifest["functions"]]
    release_symbols = [
        record["c"]["releaseFunction"]
        for record in manifest["types"]
        if record["c"]["kind"] == "opaque-handle"
    ]
    all_symbols = [*c_symbols, *release_symbols]
    if len(set(c_symbols)) != len(c_symbols) or len(set(all_symbols)) != len(all_symbols):
        raise ManifestError("manifest contains duplicate C function symbols")

    for record in [*manifest["types"], *manifest["functions"]]:
        if any(identifier not in root_requirements for identifier in record["requirementIds"]):
            raise ManifestError("declaration references an unknown requirement ID")
    requirement_lists = [
        manifest["requirementIds"],
        *(record["requirementIds"] for record in [*manifest["types"], *manifest["functions"]]),
    ]
    if any(identifiers != sorted(set(identifiers)) for identifiers in requirement_lists):
        raise ManifestError("requirement IDs must be unique and lexicographically sorted")
    for limit in manifest["limits"]:
        if limit["errorCategory"] not in error_ids:
            raise ManifestError("limit references an unknown error category")

    c_handle_names = {
        record["c"]["name"]: record
        for record in manifest["types"]
        if record["c"]["kind"] == "opaque-handle"
    }
    for record in manifest["functions"]:
        for language in ("c", "java", "python"):
            function_errors = set(record[language]["errorCategories"])
            if not function_errors <= error_ids:
                raise ManifestError("function references an unknown error category")
        params = record["c"]["parameters"]
        parameter_names = [parameter["name"] for parameter in params]
        if len(set(parameter_names)) != len(parameter_names):
            raise ManifestError("C function parameter names must be unique")
        param_by_name = {param["name"]: param for param in params}
        for param in params:
            if param["kind"] == "byte-span":
                length = param_by_name.get(param["byteLengthParameter"])
                if length is None or length["kind"] != "scalar" or length["type"] != param["byteLengthType"]:
                    raise ManifestError("byte-span length must name a matching scalar parameter")
            elif param["kind"] == "handle":
                handle_name = param["type"].split()[0].rstrip("*").strip()
                if handle_name not in c_handle_names:
                    raise ManifestError("function handle parameter references an unknown opaque type")
            elif param["kind"] == "output" and "**" in param["type"]:
                handle_name = param["type"].split()[0].strip()
                if handle_name not in c_handle_names:
                    raise ManifestError("function output references an unknown opaque type")
        if any(parameter["kind"] == "handle" for parameter in params):
            if any(
                "invalid_input" not in record[language]["errorCategories"]
                for language in ("c", "java", "python")
            ):
                raise ManifestError("handle-taking functions must map invalid_input in every adapter")
        if record["id"] in {"ttlv_value_enumeration", "ttlv_value_interval"}:
            if any(
                "invalid_input" not in record[language]["errorCategories"]
                for language in ("java", "python")
            ):
                raise ManifestError("Java and Python Enumeration/Interval constructors must map invalid_input")
        if record["id"] == "ttlv_value_boolean" and "invalid_input" not in record["c"]["errorCategories"]:
            raise ManifestError("C Boolean construction must map invalid_input")

    for record in manifest["types"]:
        if record["kind"] != "enum":
            continue
        values = record["enumRepresentation"]["values"]
        names = [entry["name"] for entry in values]
        numbers = [entry["value"] for entry in values]
        if len(set(names)) != len(names) or len(set(numbers)) != len(numbers):
            raise ManifestError("enum names and numeric values must be unique")
        storage = record["c"]["underlyingType"]
        bits = _C_INTEGER_TYPES[storage][1]
        signed = _C_INTEGER_TYPES[storage][2]
        minimum = -(1 << (bits - 1)) if signed else 0
        maximum = (1 << (bits - 1)) - 1 if signed else (1 << bits) - 1
        if any(number < minimum or number > maximum for number in numbers):
            raise ManifestError("enum value does not fit its C storage type")

    if tuple(limit["id"] for limit in manifest["limits"]) != _FIXED_LIMIT_IDS:
        raise ManifestError("manifest limits do not use the approved FR-012 order")
    if manifest["generatedOutputs"] != OUTPUTS:
        raise PathSecurityError("manifest output paths differ from the approved six destinations")


def _c_parameter_type(parameter: dict[str, Any]) -> str:
    return parameter["type"]


def _c_declaration(function: dict[str, Any]) -> str:
    parameters = function["c"]["parameters"]
    arguments = ", ".join(f"{_c_parameter_type(item)} {item['name']}" for item in parameters) or "void"
    return f"{function['c']['returnType']} {function['c']['symbol']}({arguments});"


def _rust_c_type(c_type: str) -> str:
    match = re.fullmatch(r"(const\s+)?([A-Za-z_][A-Za-z0-9_]*)(\s*\*+)?", c_type)
    if match is None:
        raise ManifestError("C signature cannot be represented in the Rust FFI mapping")
    const, base, stars = match.groups()
    rust_base = _C_INTEGER_TYPES.get(base, (base, 0, False))[0]
    pointer_count = stars.count("*") if stars else 0
    if pointer_count == 0:
        return rust_base
    pointer = "*const" if const and pointer_count == 1 else "*mut"
    return " ".join([pointer] * pointer_count + [rust_base])


def _rust_identifier(name: str) -> str:
    if name in _RUST_RAW_IDENTIFIER_FORBIDDEN:
        raise ManifestError("C parameter name cannot be represented as a Rust FFI identifier")
    return f"r#{name}" if name in _RUST_2024_KEYWORDS else name


def render_rust_ffi(manifest: dict[str, Any]) -> str:
    lines = [
        "// @generated by tools/api_manifest/generate.py; do not edit.",
        "#![allow(non_camel_case_types, non_snake_case)]",
        "",
        "pub const PUBLIC_API_MANIFEST_FORMAT_VERSION: u32 = 1;",
    ]
    emitted: set[str] = set()
    for declaration in manifest["types"]:
        c_type = declaration["c"]
        name = c_type["name"]
        if name in emitted:
            continue
        emitted.add(name)
        if c_type["kind"] == "opaque-handle":
            lines.extend(["#[repr(C)]", f"pub struct {name} {{ _private: [u8; 0] }}"])
        elif c_type["kind"] == "enum":
            storage = _C_INTEGER_TYPES[c_type["underlyingType"]][0]
            lines.append(f"pub type {name} = {storage};")
            for value in declaration["enumRepresentation"]["values"]:
                const_name = f"{name[:-2].upper()}_{re.sub(r'(?<!^)(?=[A-Z])', '_', value['name']).upper()}"
                lines.append(f"pub const {const_name}: {name} = {value['value']};")
        elif c_type["kind"] == "fixed-width-value":
            lines.extend(["#[repr(C)]", f"pub struct {name} {{"])
            for limit in manifest["limits"]:
                lines.append(f"    pub {limit['cField']}: u64,")
            lines.append("}")
        lines.append("")
    lines.extend(["unsafe extern \"C\" {"])
    for declaration in manifest["types"]:
        c_type = declaration["c"]
        if c_type["kind"] == "opaque-handle":
            lines.append(f"    pub fn {c_type['releaseFunction']}(handle: *mut {c_type['name']});")
    for function in manifest["functions"]:
        lines.append(f"    // {', '.join(function['requirementIds'])}")
        parameters = function["c"]["parameters"]
        args = ", ".join(
            f"{_rust_identifier(parameter['name'])}: {_rust_c_type(parameter['type'])}"
            for parameter in parameters
        )
        result = _rust_c_type(function["c"]["returnType"])
        lines.append(f"    pub fn {function['c']['symbol']}({args}) -> {result};")
    lines.extend(["}", ""])
    return "\n".join(lines)


def render_c_header(manifest: dict[str, Any]) -> str:
    lines = [
        "/* @generated by tools/api_manifest/generate.py; do not edit. */",
        "#ifndef KMIPKIT_H",
        "#define KMIPKIT_H",
        "#include <stdint.h>",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
    ]
    emitted: set[str] = set()
    for declaration in manifest["types"]:
        c_type = declaration["c"]
        name = c_type["name"]
        if name in emitted:
            continue
        emitted.add(name)
        if c_type["kind"] == "opaque-handle":
            lines.append(f"typedef struct {name} {name};")
        elif c_type["kind"] == "enum":
            lines.append(f"typedef {c_type['underlyingType']} {name};")
            prefix = name[:-2].upper()
            for value in declaration["enumRepresentation"]["values"]:
                const_name = f"{prefix}_{re.sub(r'(?<!^)(?=[A-Z])', '_', value['name']).upper()}"
                lines.append(f"#define {const_name} (({name}){value['value']})")
        elif c_type["kind"] == "fixed-width-value":
            lines.append("typedef struct {")
            for limit in manifest["limits"]:
                lines.append(f"    uint64_t {limit['cField']};")
            lines.append(f"}} {name};")
        lines.append("")
    for declaration in manifest["types"]:
        c_type = declaration["c"]
        if c_type["kind"] == "opaque-handle":
            lines.append(f"void {c_type['releaseFunction']}({c_type['name']} *handle);")
    for error in manifest["errorCategories"]:
        lines.append(f"#define {error['cCode']} ((int32_t){error['cValue']})")
    lines.append("")
    for function in manifest["functions"]:
        requirement_comment = ", ".join(function["requirementIds"])
        lines.append(f"/* {requirement_comment} */")
        lines.append(_c_declaration(function))
    lines.extend(["", "#ifdef __cplusplus", "}", "#endif", "#endif /* KMIPKIT_H */", ""])
    return "\n".join(lines)


def _json_literal(value: Any) -> str:
    return _dump_json(value)


def render_java_api(manifest: dict[str, Any]) -> str:
    functions = [
        {
            "id": function["id"],
            "class": function["java"]["class"],
            "method": function["java"]["method"],
            "returnType": function["java"]["returnType"],
            "parameters": function["java"]["parameters"],
            "requirementIds": function["requirementIds"],
            "errorCategories": function["java"]["errorCategories"],
        }
        for function in manifest["functions"]
    ]
    compact = _dump_json(functions)
    escaped = compact.replace("\\", "\\\\").replace('"', '\\"')
    return "\n".join([
        "// @generated by tools/api_manifest/generate.py; do not edit.",
        "package org.kmipkit.generated;",
        "",
        "/** Deterministic public API and parity metadata derived from public-api.json. */",
        "public final class ExtensionRegistryApi {",
        "    public static final int FORMAT_VERSION = 1;",
        f'    public static final String FUNCTION_METADATA_JSON = "{escaped}";',
        "    private ExtensionRegistryApi() {}",
        "}",
        "",
    ])


def render_java_parity(manifest: dict[str, Any]) -> str:
    requirement_ids = _dump_json(manifest["requirementIds"])
    limits = _dump_json(manifest["limits"])
    escaped_requirements = requirement_ids.replace("\\", "\\\\").replace('"', '\\"')
    escaped_limits = limits.replace("\\", "\\\\").replace('"', '\\"')
    return "\n".join([
        "// @generated by tools/api_manifest/generate.py; do not edit.",
        "package org.kmipkit.generated;",
        "",
        "/** Registry contract fixture metadata shared with adapter parity checks. */",
        "public final class ExtensionRegistryParityFixtures {",
        f'    public static final String REQUIREMENT_IDS_JSON = "{escaped_requirements}";',
        f'    public static final String LIMITS_JSON = "{escaped_limits}";',
        "    private ExtensionRegistryParityFixtures() {}",
        "}",
        "",
    ])


def render_python_api(manifest: dict[str, Any]) -> str:
    lines = [
        '"""Generated registry API signature metadata. Do not edit."""',
        "from __future__ import annotations",
        "import json as _json",
        "",
        f"FORMAT_VERSION = {manifest['formatVersion']}",
        "FUNCTIONS = (",
    ]
    for function in manifest["functions"]:
        record = {
            "id": function["id"],
            "name": function["python"]["function"],
            "returnType": function["python"]["returnType"],
            "parameters": function["python"]["parameters"],
            "requirementIds": function["requirementIds"],
            "errorCategories": function["python"]["errorCategories"],
        }
        lines.append(
            f"    _json.loads({_json_literal(_dump_json(record))}),"
        )
    lines.extend([")", "", "__all__ = ['FORMAT_VERSION', 'FUNCTIONS']", ""])
    return "\n".join(lines)


def render_parity_fixtures(manifest: dict[str, Any]) -> str:
    return _dump_json(manifest, indent=2) + "\n"


def render_outputs(manifest: dict[str, Any]) -> dict[str, bytes]:
    renderers = {
        "rustFfi": render_rust_ffi,
        "cHeader": render_c_header,
        "javaApi": render_java_api,
        "javaParityTests": render_java_parity,
        "pythonApi": render_python_api,
        "parityFixtures": render_parity_fixtures,
    }
    return {OUTPUTS[key]: renderers[key](manifest).encode("utf-8") for key in OUTPUTS}


def _is_reparse_point(path: Path) -> bool:
    try:
        metadata = path.lstat()
    except FileNotFoundError:
        return False
    if stat.S_ISLNK(metadata.st_mode) or getattr(path, "is_junction", lambda: False)():
        return True
    return bool(getattr(metadata, "st_file_attributes", 0) & 0x400)


def _safe_destination(root: Path, relative: str) -> Path:
    candidate = Path(relative)
    if candidate.is_absolute() or any(part in ("", ".", "..") for part in candidate.parts):
        raise PathSecurityError("generated destination is not a safe relative path")
    destination = root.joinpath(candidate)
    current = root
    for part in candidate.parts:
        current = current / part
        if _is_reparse_point(current):
            raise PathSecurityError("generated destination traverses a symbolic link or reparse point")
        if current.exists() and current != destination and not current.is_dir():
            raise PathSecurityError("generated destination parent is not a directory")
    try:
        destination.resolve(strict=False).relative_to(root)
    except (OSError, ValueError) as error:
        raise PathSecurityError("generated destination escapes the repository root") from error
    if destination.exists() and not destination.is_file():
        raise PathSecurityError("generated destination is not a regular file")
    return destination


def _preflight_outputs(root: Path, output_bytes: dict[str, bytes]) -> dict[str, Path]:
    return {relative: _safe_destination(root, relative) for relative in output_bytes}


def _atomic_write(destination: Path, data: bytes, root: Path, relative: str) -> None:
    _safe_destination(root, relative)
    destination.parent.mkdir(parents=True, exist_ok=True)
    _safe_destination(root, relative)
    temporary_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile("wb", dir=destination.parent, prefix=".kmipkit-api-", delete=False) as temporary:
            temporary_name = temporary.name
            temporary.write(data)
            temporary.flush()
            os.fsync(temporary.fileno())
        _safe_destination(root, relative)
        os.replace(temporary_name, destination)
        temporary_name = None
    finally:
        if temporary_name is not None:
            try:
                os.unlink(temporary_name)
            except FileNotFoundError:
                pass


def _run(root_path: Path, write: bool) -> int:
    try:
        root = root_path.resolve(strict=True)
        manifest = _load_json(root, MANIFEST_PATH, MAX_MANIFEST_BYTES)
        schema = _load_json(root, SCHEMA_PATH, MAX_SCHEMA_BYTES)
        if not isinstance(manifest, dict) or not isinstance(schema, dict):
            raise ManifestError("manifest and schema roots must be JSON objects")
        _validate_schema(manifest, schema)
        _validate_references(manifest)
        outputs = render_outputs(manifest)
        destinations = _preflight_outputs(root, outputs)
        if write:
            for relative, data in outputs.items():
                _atomic_write(destinations[relative], data, root, relative)
            print(f"generated registry API manifest outputs: {len(outputs)} files")
            return 0
        stale = []
        for relative, expected in outputs.items():
            try:
                actual = destinations[relative].read_bytes()
            except FileNotFoundError:
                stale.append(relative)
                continue
            if actual != expected:
                stale.append(relative)
        if stale:
            print(f"registry API outputs are stale or missing: {len(stale)} file(s)", file=sys.stderr)
            return 1
        print(f"registry API manifest outputs verified: {len(outputs)} files")
        return 0
    except (ManifestError, PathSecurityError, RecursionError, OverflowError):
        print("registry API generation failed: manifest or path validation failed", file=sys.stderr)
        return 2
    except OSError:
        print("registry API generation failed: repository I/O failed", file=sys.stderr)
        return 2


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path.cwd())
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="write the six generated API files")
    mode.add_argument("--check", action="store_true", help="compare generated files without writing")
    arguments = parser.parse_args(argv)
    return _run(arguments.repo_root, arguments.write)


if __name__ == "__main__":
    raise SystemExit(main())
