/* @generated by tools/api_manifest/generate.py; do not edit. */
#ifndef KMIPKIT_H
#define KMIPKIT_H
#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#endif

typedef struct kmipkit_extension_identity_t kmipkit_extension_identity_t;

typedef struct kmipkit_extension_compatibility_t kmipkit_extension_compatibility_t;

typedef struct kmipkit_ttlv_path_t kmipkit_ttlv_path_t;

typedef struct kmipkit_extension_discriminator_t kmipkit_extension_discriminator_t;

typedef struct kmipkit_extension_schema_t kmipkit_extension_schema_t;

typedef struct kmipkit_extension_information_t kmipkit_extension_information_t;

typedef struct {
    uint64_t max_definitions;
    uint64_t max_schema_nodes;
    uint64_t max_child_rules_per_structure;
    uint64_t max_text_bytes_per_field;
    uint64_t max_registry_text_bytes;
    uint64_t max_discriminator_scalar_bytes;
    uint64_t max_total_discriminator_scalar_bytes;
    uint64_t max_constraint_members_per_rule;
    uint64_t max_total_constraint_members;
    uint64_t max_payload_index_records;
    uint64_t max_lookup_comparisons;
    uint64_t max_depth;
} kmipkit_extension_registry_limits_t;

typedef struct kmipkit_extension_definition_t kmipkit_extension_definition_t;

typedef struct kmipkit_client_extension_registry_t kmipkit_client_extension_registry_t;

typedef struct kmipkit_client_configuration_t kmipkit_client_configuration_t;

typedef struct kmipkit_validated_extension_value_t kmipkit_validated_extension_value_t;

typedef struct kmipkit_registered_extension_value_t kmipkit_registered_extension_value_t;

typedef struct kmipkit_client_request_message_extension_t kmipkit_client_request_message_extension_t;

typedef struct kmipkit_ttlv_structure_t kmipkit_ttlv_structure_t;

typedef struct kmipkit_client_batch_item_t kmipkit_client_batch_item_t;

typedef struct kmipkit_extension_child_rule_t kmipkit_extension_child_rule_t;

typedef struct kmipkit_extension_order_constraint_t kmipkit_extension_order_constraint_t;

typedef uint8_t kmipkit_ttlv_item_type_t;
#define KMIPKIT_TTLV_ITEM_TYPE_STRUCTURE ((kmipkit_ttlv_item_type_t)1)
#define KMIPKIT_TTLV_ITEM_TYPE_INTEGER ((kmipkit_ttlv_item_type_t)2)
#define KMIPKIT_TTLV_ITEM_TYPE_LONG_INTEGER ((kmipkit_ttlv_item_type_t)3)
#define KMIPKIT_TTLV_ITEM_TYPE_BIG_INTEGER ((kmipkit_ttlv_item_type_t)4)
#define KMIPKIT_TTLV_ITEM_TYPE_ENUMERATION ((kmipkit_ttlv_item_type_t)5)
#define KMIPKIT_TTLV_ITEM_TYPE_BOOLEAN ((kmipkit_ttlv_item_type_t)6)
#define KMIPKIT_TTLV_ITEM_TYPE_TEXT_STRING ((kmipkit_ttlv_item_type_t)7)
#define KMIPKIT_TTLV_ITEM_TYPE_BYTE_STRING ((kmipkit_ttlv_item_type_t)8)
#define KMIPKIT_TTLV_ITEM_TYPE_DATE_TIME ((kmipkit_ttlv_item_type_t)9)
#define KMIPKIT_TTLV_ITEM_TYPE_INTERVAL ((kmipkit_ttlv_item_type_t)10)
#define KMIPKIT_TTLV_ITEM_TYPE_DATE_TIME_EXTENDED ((kmipkit_ttlv_item_type_t)11)

typedef struct kmipkit_ttlv_value_t kmipkit_ttlv_value_t;

typedef struct kmipkit_extension_recognition_t kmipkit_extension_recognition_t;

typedef struct kmipkit_raw_tag_t kmipkit_raw_tag_t;

typedef struct kmipkit_tag_t kmipkit_tag_t;

typedef struct kmipkit_ttlv_item_t kmipkit_ttlv_item_t;

typedef struct kmipkit_codec_limits_t kmipkit_codec_limits_t;

typedef struct kmipkit_ttlv_structure_view_t kmipkit_ttlv_structure_view_t;

typedef struct kmipkit_ttlv_item_view_t kmipkit_ttlv_item_view_t;

typedef struct kmipkit_ttlv_value_view_t kmipkit_ttlv_value_view_t;

void kmipkit_extension_identity_release(kmipkit_extension_identity_t *handle);
void kmipkit_extension_compatibility_release(kmipkit_extension_compatibility_t *handle);
void kmipkit_ttlv_path_release(kmipkit_ttlv_path_t *handle);
void kmipkit_extension_discriminator_release(kmipkit_extension_discriminator_t *handle);
void kmipkit_extension_schema_release(kmipkit_extension_schema_t *handle);
void kmipkit_extension_information_release(kmipkit_extension_information_t *handle);
void kmipkit_extension_definition_release(kmipkit_extension_definition_t *handle);
void kmipkit_client_extension_registry_release(kmipkit_client_extension_registry_t *handle);
void kmipkit_client_configuration_release(kmipkit_client_configuration_t *handle);
void kmipkit_validated_extension_value_release(kmipkit_validated_extension_value_t *handle);
void kmipkit_registered_extension_value_release(kmipkit_registered_extension_value_t *handle);
void kmipkit_client_request_message_extension_release(kmipkit_client_request_message_extension_t *handle);
void kmipkit_ttlv_structure_release(kmipkit_ttlv_structure_t *handle);
void kmipkit_client_batch_item_release(kmipkit_client_batch_item_t *handle);
void kmipkit_extension_child_rule_release(kmipkit_extension_child_rule_t *handle);
void kmipkit_extension_order_constraint_release(kmipkit_extension_order_constraint_t *handle);
void kmipkit_ttlv_value_release(kmipkit_ttlv_value_t *handle);
void kmipkit_extension_recognition_release(kmipkit_extension_recognition_t *handle);
void kmipkit_raw_tag_release(kmipkit_raw_tag_t *handle);
void kmipkit_tag_release(kmipkit_tag_t *handle);
void kmipkit_ttlv_item_release(kmipkit_ttlv_item_t *handle);
void kmipkit_codec_limits_release(kmipkit_codec_limits_t *handle);
void kmipkit_ttlv_structure_view_release(kmipkit_ttlv_structure_view_t *handle);
void kmipkit_ttlv_item_view_release(kmipkit_ttlv_item_view_t *handle);
void kmipkit_ttlv_value_view_release(kmipkit_ttlv_value_view_t *handle);
#define KMIPKIT_ERROR_COMPATIBILITY_MISMATCH ((int32_t)1)
#define KMIPKIT_ERROR_DUPLICATE_KEY ((int32_t)2)
#define KMIPKIT_ERROR_INVALID_IDENTITY ((int32_t)3)
#define KMIPKIT_ERROR_INVALID_INPUT ((int32_t)4)
#define KMIPKIT_ERROR_INVALID_SCHEMA ((int32_t)5)
#define KMIPKIT_ERROR_RESOURCE_LIMIT ((int32_t)6)

/* KMIPKIT-0012-FR-002, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_extension_identity_create(const uint8_t * vendor_identifier_data, uint64_t vendor_identifier_length, const uint8_t * name_data, uint64_t name_length, const uint8_t * version_data, uint64_t version_length, kmipkit_extension_identity_t ** out_identity);
/* KMIPKIT-0012-FR-002, KMIPKIT-0012-FR-003, KMIPKIT-0012-FR-004, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_extension_definition_create(kmipkit_extension_identity_t * identity, kmipkit_extension_compatibility_t * compatibility, kmipkit_extension_discriminator_t * discriminator, kmipkit_extension_schema_t * schema, kmipkit_extension_definition_t ** out_definition);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-011, KMIPKIT-0012-FR-012 */
int32_t kmipkit_extension_definition_validate(kmipkit_extension_definition_t * definition, kmipkit_ttlv_structure_t * value, kmipkit_validated_extension_value_t ** out_value, kmipkit_codec_limits_t * limits);
/* KMIPKIT-0012-FR-001, KMIPKIT-0012-FR-003, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_client_configuration_create(kmipkit_client_extension_registry_t * extension_registry, kmipkit_client_configuration_t ** out_configuration);
/* KMIPKIT-0012-FR-001, KMIPKIT-0012-FR-003, KMIPKIT-0012-FR-010 */
int32_t kmipkit_client_configuration_extension_registry(kmipkit_client_configuration_t * configuration, kmipkit_client_extension_registry_t ** out_registry);
/* For nullable handle arrays, NULL is valid only when the linked count is zero.
 * Implementations must check the count before reading elements and return
 * invalid_input when a NULL array has a nonzero count. */
/* KMIPKIT-0012-FR-001, KMIPKIT-0012-FR-003, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_client_extension_registry_create(kmipkit_extension_definition_t ** definitions, uint64_t definition_count, uint64_t max_definitions, uint64_t max_schema_nodes, uint64_t max_child_rules_per_structure, uint64_t max_text_bytes_per_field, uint64_t max_registry_text_bytes, uint64_t max_discriminator_scalar_bytes, uint64_t max_total_discriminator_scalar_bytes, uint64_t max_constraint_members_per_rule, uint64_t max_total_constraint_members, uint64_t max_payload_index_records, uint64_t max_lookup_comparisons, uint64_t max_depth, kmipkit_client_extension_registry_t ** out_registry);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-006, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-008, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_client_extension_registry_inspect(kmipkit_client_extension_registry_t * registry, const uint8_t * vendor_identifier_data, uint64_t vendor_identifier_length, kmipkit_ttlv_structure_t * value, kmipkit_extension_recognition_t ** out_value, kmipkit_codec_limits_t * limits);
/* KMIPKIT-0012-FR-009, KMIPKIT-0012-FR-010 */
int32_t kmipkit_client_extension_registry_definition_count(kmipkit_client_extension_registry_t * registry, uint64_t * out_count);
/* KMIPKIT-0012-FR-009, KMIPKIT-0012-FR-010 */
int32_t kmipkit_client_extension_registry_definition_at(kmipkit_client_extension_registry_t * registry, uint64_t index, kmipkit_extension_definition_t ** out_definition);
/* KMIPKIT-0012-FR-002, KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-011, KMIPKIT-0012-FR-012 */
int32_t kmipkit_client_extension_registry_validate(kmipkit_client_extension_registry_t * registry, kmipkit_extension_identity_t * identity, kmipkit_ttlv_structure_t * value, kmipkit_codec_limits_t * limits, kmipkit_registered_extension_value_t ** out_value);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-011 */
int32_t kmipkit_client_request_message_extension_create(kmipkit_registered_extension_value_t * value, uint8_t criticality_indicator, kmipkit_client_request_message_extension_t ** out_extension);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-011 */
int32_t kmipkit_client_batch_item_with_extension(kmipkit_client_batch_item_t * item, kmipkit_client_request_message_extension_t * extension, kmipkit_client_batch_item_t ** out_item);
/* KMIPKIT-0012-FR-002, KMIPKIT-0012-FR-003, KMIPKIT-0012-FR-010 */
int32_t kmipkit_extension_compatibility_create(uint8_t kmip_min_major, uint8_t kmip_min_minor, uint8_t kmip_max_major, uint8_t kmip_max_minor, const uint8_t * kmipkit_minimum_data, uint64_t kmipkit_minimum_length, const uint8_t * kmipkit_maximum_data, uint64_t kmipkit_maximum_length, kmipkit_extension_compatibility_t ** out_compatibility);
/* KMIPKIT-0012-FR-002, KMIPKIT-0012-FR-006, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_ttlv_path_create(uint32_t first_tag, kmipkit_ttlv_path_t ** out_path);
/* KMIPKIT-0012-FR-002, KMIPKIT-0012-FR-006, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_ttlv_path_with_child_tag(kmipkit_ttlv_path_t * path, uint32_t tag, kmipkit_ttlv_path_t ** out_path);
/* KMIPKIT-0012-FR-002, KMIPKIT-0012-FR-006, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_extension_discriminator_create(kmipkit_ttlv_path_t * path, kmipkit_ttlv_value_t * scalar_value, kmipkit_extension_discriminator_t ** out_discriminator);
/* KMIPKIT-0012-FR-004, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_extension_schema_scalar(uint32_t item_type, kmipkit_extension_schema_t ** out_schema);
/* For nullable handle arrays, NULL is valid only when the linked count is zero.
 * Implementations must check the count before reading elements and return
 * invalid_input when a NULL array has a nonzero count. */
/* KMIPKIT-0012-FR-004, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_extension_schema_structure(kmipkit_extension_child_rule_t ** children, uint64_t child_count, kmipkit_extension_order_constraint_t ** order_constraints, uint64_t order_constraint_count, uint8_t preserve_undeclared_children, kmipkit_extension_schema_t ** out_schema);
/* KMIPKIT-0012-FR-004, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_extension_child_rule_required(uint32_t tag, kmipkit_extension_schema_t * schema, kmipkit_extension_child_rule_t ** out_rule);
/* KMIPKIT-0012-FR-004, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_extension_child_rule_optional(uint32_t tag, kmipkit_extension_schema_t * schema, kmipkit_extension_child_rule_t ** out_rule);
/* KMIPKIT-0012-FR-004, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_extension_child_rule_repeated(uint32_t tag, kmipkit_extension_schema_t * schema, kmipkit_extension_child_rule_t ** out_rule);
/* KMIPKIT-0012-FR-004, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_extension_order_constraint_create(uint32_t before_tag, uint32_t after_tag, kmipkit_extension_order_constraint_t ** out_constraint);
/* KMIPKIT-0012-FR-004, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_extension_schema_minimum_length(kmipkit_extension_schema_t * schema, uint64_t bytes, kmipkit_extension_schema_t ** out_schema);
/* KMIPKIT-0012-FR-004, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_extension_schema_maximum_length(kmipkit_extension_schema_t * schema, uint64_t bytes, kmipkit_extension_schema_t ** out_schema);
/* KMIPKIT-0012-FR-004, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_extension_schema_signed_numeric_range(kmipkit_extension_schema_t * schema, int64_t minimum, int64_t maximum, kmipkit_extension_schema_t ** out_schema);
/* KMIPKIT-0012-FR-004, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_extension_schema_unsigned_numeric_range(kmipkit_extension_schema_t * schema, uint64_t minimum, uint64_t maximum, kmipkit_extension_schema_t ** out_schema);
/* KMIPKIT-0012-FR-004, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_extension_schema_allowed_enumeration(kmipkit_extension_schema_t * schema, uint32_t value, kmipkit_extension_schema_t ** out_schema);
/* KMIPKIT-0012-FR-004, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_extension_schema_allowed_bit_mask(kmipkit_extension_schema_t * schema, uint32_t value, kmipkit_extension_schema_t ** out_schema);
/* KMIPKIT-0012-FR-004, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_extension_schema_required_bit_mask(kmipkit_extension_schema_t * schema, uint32_t value, kmipkit_extension_schema_t ** out_schema);
/* KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_extension_registry_limits_default_values(uint64_t * out_max_definitions, uint64_t * out_max_schema_nodes, uint64_t * out_max_child_rules_per_structure, uint64_t * out_max_text_bytes_per_field, uint64_t * out_max_registry_text_bytes, uint64_t * out_max_discriminator_scalar_bytes, uint64_t * out_max_total_discriminator_scalar_bytes, uint64_t * out_max_constraint_members_per_rule, uint64_t * out_max_total_constraint_members, uint64_t * out_max_payload_index_records, uint64_t * out_max_lookup_comparisons, uint64_t * out_max_depth);
/* KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_extension_registry_limits_validate(uint64_t max_definitions, uint64_t max_schema_nodes, uint64_t max_child_rules_per_structure, uint64_t max_text_bytes_per_field, uint64_t max_registry_text_bytes, uint64_t max_discriminator_scalar_bytes, uint64_t max_total_discriminator_scalar_bytes, uint64_t max_constraint_members_per_rule, uint64_t max_total_constraint_members, uint64_t max_payload_index_records, uint64_t max_lookup_comparisons, uint64_t max_depth);
/* KMIPKIT-0012-FR-009, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_extension_information_create(const uint8_t * extension_name_data, uint64_t extension_name_length, kmipkit_extension_information_t ** out_information);
/* KMIPKIT-0012-FR-009, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_extension_information_tag(kmipkit_extension_information_t * information, uint32_t tag, kmipkit_extension_information_t ** out_information);
/* KMIPKIT-0012-FR-009, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_extension_information_type(kmipkit_extension_information_t * information, uint32_t type, kmipkit_extension_information_t ** out_information);
/* KMIPKIT-0012-FR-009, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_extension_information_enumeration(kmipkit_extension_information_t * information, uint32_t enumeration, kmipkit_extension_information_t ** out_information);
/* KMIPKIT-0012-FR-009, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_extension_information_attribute(kmipkit_extension_information_t * information, uint8_t attribute, kmipkit_extension_information_t ** out_information);
/* KMIPKIT-0012-FR-009, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_extension_information_parent_structure_tag(kmipkit_extension_information_t * information, uint32_t parent_structure_tag, kmipkit_extension_information_t ** out_information);
/* KMIPKIT-0012-FR-009, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_extension_information_description(kmipkit_extension_information_t * information, const uint8_t * description_data, uint64_t description_length, kmipkit_extension_information_t ** out_information);
/* KMIPKIT-0012-FR-009, KMIPKIT-0012-FR-010 */
int32_t kmipkit_extension_information_to_ttlv(kmipkit_extension_information_t * information, kmipkit_ttlv_structure_t ** out_structure);
/* KMIPKIT-0012-FR-009, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_extension_definition_with_information(kmipkit_extension_definition_t * definition, kmipkit_extension_information_t * information, kmipkit_extension_definition_t ** out_definition);
/* KMIPKIT-0012-FR-002, KMIPKIT-0012-FR-009, KMIPKIT-0012-FR-010 */
int32_t kmipkit_extension_definition_identity(kmipkit_extension_definition_t * definition, kmipkit_extension_identity_t ** out_identity);
/* KMIPKIT-0012-FR-009, KMIPKIT-0012-FR-010 */
int32_t kmipkit_extension_definition_information(kmipkit_extension_definition_t * definition, kmipkit_extension_information_t ** out_information);
/* KMIPKIT-0012-FR-009, KMIPKIT-0012-FR-010 */
int32_t kmipkit_client_extension_registry_definition_for_identity(kmipkit_client_extension_registry_t * registry, kmipkit_extension_identity_t * identity, kmipkit_extension_definition_t ** out_definition);
/* KMIPKIT-0012-FR-006, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_extension_recognition_is_recognized(kmipkit_extension_recognition_t * recognition, uint32_t * out_recognized);
/* KMIPKIT-0012-FR-006, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_extension_recognition_validated_value(kmipkit_extension_recognition_t * recognition, kmipkit_validated_extension_value_t ** out_value);
/* KMIPKIT-0012-FR-006, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_extension_recognition_generic_value(kmipkit_extension_recognition_t * recognition, kmipkit_ttlv_structure_view_t ** out_value);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_validated_extension_value_identity(kmipkit_validated_extension_value_t * value, kmipkit_extension_identity_t ** out_identity);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-011 */
int32_t kmipkit_validated_extension_value_generic_value(kmipkit_validated_extension_value_t * value, kmipkit_ttlv_structure_view_t ** out_structure);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_validated_extension_value_value_at(kmipkit_validated_extension_value_t * value, kmipkit_ttlv_path_t * path, kmipkit_ttlv_value_view_t ** out_value);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_raw_tag_create(uint32_t raw, kmipkit_raw_tag_t ** out_raw_tag);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_raw_tag_value(kmipkit_raw_tag_t * raw_tag, uint32_t * out_raw);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_raw_tag_try_checked(kmipkit_raw_tag_t * raw_tag, kmipkit_tag_t ** out_tag);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_tag_value(kmipkit_tag_t * tag, uint32_t * out_raw);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_codec_limits_defaults(kmipkit_codec_limits_t ** out_limits);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_codec_limits_create(uint64_t max_message_bytes, uint64_t max_structure_depth, uint64_t max_elements, kmipkit_codec_limits_t ** out_limits);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_codec_limits_max_message_bytes(kmipkit_codec_limits_t * limits, uint64_t * max_message_bytes);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_codec_limits_max_structure_depth(kmipkit_codec_limits_t * limits, uint64_t * max_structure_depth);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_codec_limits_max_elements(kmipkit_codec_limits_t * limits, uint64_t * max_elements);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_value_integer(int32_t value, kmipkit_ttlv_value_t ** out_value);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_value_long_integer(int64_t value, kmipkit_ttlv_value_t ** out_value);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_value_enumeration(uint32_t value, kmipkit_ttlv_value_t ** out_value);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_value_boolean(uint8_t value, kmipkit_ttlv_value_t ** out_value);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_value_date_time(int64_t value, kmipkit_ttlv_value_t ** out_value);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_value_interval(uint32_t value, kmipkit_ttlv_value_t ** out_value);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_value_date_time_extended(int64_t value, kmipkit_ttlv_value_t ** out_value);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_ttlv_value_big_integer(kmipkit_codec_limits_t * limits, const uint8_t * value, uint64_t value_length, kmipkit_ttlv_value_t ** out_value);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_ttlv_value_text_string(kmipkit_codec_limits_t * limits, const uint8_t * value, uint64_t value_length, kmipkit_ttlv_value_t ** out_value);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_ttlv_value_byte_string(kmipkit_codec_limits_t * limits, const uint8_t * value, uint64_t value_length, kmipkit_ttlv_value_t ** out_value);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_ttlv_value_structure(kmipkit_ttlv_structure_t * structure, kmipkit_codec_limits_t * limits, kmipkit_ttlv_value_t ** out_value);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_structure_create(kmipkit_ttlv_structure_t ** out_structure);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_ttlv_item_create(kmipkit_tag_t * tag, kmipkit_ttlv_value_t * value, kmipkit_codec_limits_t * limits, kmipkit_ttlv_item_t ** out_item);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010, KMIPKIT-0012-FR-012 */
int32_t kmipkit_ttlv_structure_with_item(kmipkit_ttlv_structure_t * structure, kmipkit_ttlv_item_t * item, kmipkit_codec_limits_t * limits, kmipkit_ttlv_structure_t ** out_structure);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_structure_view(kmipkit_ttlv_structure_t * structure, kmipkit_ttlv_structure_view_t ** out_view);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_structure_view_item_count(kmipkit_ttlv_structure_view_t * view, uint64_t * out_count);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_structure_view_item_at(kmipkit_ttlv_structure_view_t * view, uint64_t index, kmipkit_ttlv_item_view_t ** out_item);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_item_view_tag(kmipkit_ttlv_item_view_t * view, kmipkit_tag_t ** out_tag);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_item_view_type(kmipkit_ttlv_item_view_t * view, uint8_t * out_item_type);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_item_view_value(kmipkit_ttlv_item_view_t * view, kmipkit_ttlv_value_view_t ** out_value);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_value_view(kmipkit_ttlv_value_t * value, kmipkit_ttlv_value_view_t ** out_view);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_value_view_type(kmipkit_ttlv_value_view_t * view, uint8_t * out_item_type);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_value_view_structure(kmipkit_ttlv_value_view_t * view, kmipkit_ttlv_structure_view_t ** out_structure);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_value_view_integer(kmipkit_ttlv_value_view_t * view, int32_t * out_value);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_value_view_long_integer(kmipkit_ttlv_value_view_t * view, int64_t * out_value);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_value_view_enumeration(kmipkit_ttlv_value_view_t * view, uint32_t * out_value);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_value_view_boolean(kmipkit_ttlv_value_view_t * view, uint8_t * out_value);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_value_view_date_time(kmipkit_ttlv_value_view_t * view, int64_t * out_value);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_value_view_interval(kmipkit_ttlv_value_view_t * view, uint32_t * out_value);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_value_view_date_time_extended(kmipkit_ttlv_value_view_t * view, int64_t * out_value);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_value_view_byte_length(kmipkit_ttlv_value_view_t * view, uint64_t * out_length);
/* KMIPKIT-0012-FR-005, KMIPKIT-0012-FR-007, KMIPKIT-0012-FR-010 */
int32_t kmipkit_ttlv_value_view_byte_at(kmipkit_ttlv_value_view_t * view, uint64_t index, uint8_t * out_byte);

#ifdef __cplusplus
}
#endif
#endif /* KMIPKIT_H */
